### ISSUE TITLE
Modify eigenPSF signs so that the prox operator input is always a "positive" feature

### ISSUE THREAD

**Issue by tobias-liaudat** [aziz-ayed/denoising#9]
Le problème que j’ai mentioné avant c’est le suivant :
Quand on fait l’estimation d’eigenPSFs on est en train de faire un factorisation de matrices où on a, features x poids. Comme on optimise sur les deux mais pas au même temps on a un indetermination du signe. C’est-à-dire que la solution `good_psf = feature x weight`  est égal à `good_psf = -feature x -weight` . Vu que dans la factorisation on peut très bien multiplier les deux par -1.

Le problème vient du fait que nos réseaux n’aiment pas travailler avec des choses de différent signe comme ça. La performance va tomber. On aimerai travailler avec des features plutôt positives (où la grand part des coefficients son positives mais il y a pas besoin que tous soient positives)

Alors, on doit modifier des choses :

- [ ] Correct the sing of eigenPSF dataset before we train the networks. 
- How? Using abs(eigenPSF) is a very bad idea. What we want is to multiply by -1 the eigenPSFs where `np.sum(eigenPSF) < 0 ` so that for all the eigenPSFs we have `np.sum(eigenPSF) > 0` .

- [ ] Apply the same correction for the eigenPSFs that enter the network in the MCCD algorithm. So that the network has as input only eigenPSF with `np.sum(eigenPSF) > 0` .

So the pipeline would be: `input_eigenPSF -> calculate sign based on np.sum(eigenPSF)  -> denoise(eigenPSF) -> restore original sign`

**Comment by tobias-liaudat** [comment]
@aziz-ayed is this done? If it is the case, have you pushed it to the repo? Where?

**Comment by aziz-ayed** [comment]
Yes! You can find it in the op function of the class Learnlets, where you transform the image via `multiple` before applying the denoising [Link](https://github.com/aziz-ayed/mccd/blob/8bfd090981360761f607040167bff87e46e3d5bc/mccd/proxs.py#L271)
For the training, this is done in the script when loading the dataset, in the following link [Link](https://github.com/aziz-ayed/denoising/blob/e746f2825ae7ed808180aca3802f8ba95c7ec5c9/submission_scripts/training_learnlets/learnlets_256.py#L28 )
